server:
  port: 9008
spring:
  application:
    name: xc-order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.80.131:3306/xc?characterEncoding=utf-8
    username: root
    password: ZUIEWANGGUAN
  jpa:
    show-sql: true
    database: mysql
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka/
  instance:
    prefer-ip-address: true